"""comment

Revision ID: 41acc270e965
Revises: 4da0918dd83b
Create Date: 2024-05-14 18:20:03.729724

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '41acc270e965'
down_revision: Union[str, None] = '4da0918dd83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'is_paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
