"""comment

Revision ID: 5cc73ffee1c0
Revises: 41acc270e965
Create Date: 2024-05-14 19:43:19.914815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cc73ffee1c0'
down_revision: Union[str, None] = '41acc270e965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'uuid',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint('invoice_invoice_id_key', 'invoice', type_='unique')
    op.create_unique_constraint(None, 'invoice', ['uuid'])
    op.drop_column('invoice', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('invoice_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'invoice', type_='unique')
    op.create_unique_constraint('invoice_invoice_id_key', 'invoice', ['invoice_id'])
    op.alter_column('invoice', 'uuid',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
