"""comment

Revision ID: cc0498fe90a6
Revises: ccb8424760c8
Create Date: 2024-05-14 14:20:55.584775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0498fe90a6'
down_revision: Union[str, None] = 'ccb8424760c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('payment_system_name', sa.Enum('CRYPTOCLOUD', 'ROBOKASSA', name='paymentsystems'), nullable=False),
    sa.Column('service_system_name', sa.Enum('LINGOBOT', 'QUICKSPEAK', 'IMVO', name='servicesystems'), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('time_create', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    # ### end Alembic commands ###
